#ifndef __INC_PYTHON_uiscriptlib_MANAGER_H__
#define __INC_PYTHON_uiscriptlib_MANAGER_H__
#define inituiscriptlibManager inituiscriptlib
/* uiscriptlib module */
/* uiscriptlib.isExist */
/* uiscriptlib.moduleImport */
/* uiscriptlib.getList */
/* this lib includes modules under this lines.
	acceptguildwardialog
	acce_absorbwindow
	adminmanagerwindow
	AmuletInformation_Window
	atlaswindow
	attachstonedialog
	ban_panel
	battlepass
	beltinventorywindow
	biologmanageralert
	biologmanagerwindow
	buildguildbuildingwindow
	buyfailpopupdialog
	changegradenamedialog
	changepassworddialog
	characterwindow
	CostumeWindow
	createcharacterwindow
	cuberenewalwindow
	declareguildwardialog
	discarditemwindow
	doubleinputdialogwithdescription
	DungeonInfo_Main
	DungeonInfo_Ranking
	DungeonTaskWindow
	equipmentdialog
	exchangedialog_new
	expandedmoneytaskbar
	expandedtaskbar
	findletterswindow
	gameoptiondialog
	gameoptiondialog_formobile
	gamewindow
	gaya_crafting
	gaya_market
	gmidlepanel
	guildwindow
	guildwindow_baseinfopage
	guildwindow_boardpage
	guildwindow_gradepage
	guildwindow_guildinfopage
	guildwindow_guildinfopage_eu
	guildwindow_guildskillpage
	guildwindow_memberpage
	HandSwitcher_Window
	helpwindow
	helpwindow2
	HunterMission_Window
	idlepanelanswer
	imekor
	inputdialog
	inputdialogofflineshop
	inputdialogwithdescription
	inputdialogwithdescription2
	inventorymenu
	inventorywindow
	itemshop_main
	item_opener
	item_splitter
	legendary_stones_crafting_minerals
	legendary_stones_crafting_shards
	legendary_stones_crafting_stones
	legendary_stones_refine
	loadingwindow
	loginwindow
	luckyboxwindow
	maintenance_alert
	maintenance_panel
	mallwindow
	marblemanagerwindow
	marklistwindow
	messengerwindow
	minimap
	moneyinputdialog
	moneyinputdialogofflineshop
	mousebuttonwindow
	musiclistwindow
	myshopdecorationwindow
	offline_shop_builder
	offline_shop_editor
	offline_shop_manager
	offline_shop_viewer
	oxdialog
	partymemberinfoboard
	passworddialog
	pickmoneydialog
	popupdialog
	popupsystem_window
	positionsmanagerwindow
	previewwindow
	privateshopbuilder
	questdialog
	questioncopybonusdialog
	questiondialog
	questiondialog2
	questiondialog3
	questiondialogadmin
	questiondialogmultiline
	questiondialogofflineshop
	questiondialogsort
	refactoredoptions
	refinedialog
	refineelementchange
	refineelementdialog
	restartdialog
	rightmousebuttonwindow
	safeboxwindow
	sash_absorption
	sash_combination
	scalingoption_main
	SelectCharacterWindow
	selectempirewindow
	selectitemwindow
	selectskillwindow
	shopdialog
	shopsearchwindow
	specialstorage
	systemdialog
	systemdialog_forportal
	systemoptiondialog
	taskbar
	teleport_manager_window
	timewizard_dialog
	tombola_window
	transmutation
	webloadingwindow
	webwindow
	whisperdialog
	zuopanelhelper
	zuo_event
*/
void inituiscriptlibManager();
#endif
