#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	cff
	check_bad_files
	colorInfo
	consoleModule
	constInfo
	debugInfo
	dragon_soul_refine_settings
	emotion
	equipmentSet
	exception
	game
	grid
	helper
	inGameWiki
	ingamewikiconfig
	inGameWikiUI
	interfaceModule
	introCreate
	introEmpire
	introinterface
	introLoading
	introLogin
	introLogo
	introSelect
	introTest
	itemwrapper
	localeInfo
	mouseModule
	musicInfo
	networkModule
	playerSettingModule
	Prototype
	pyaudio
	queuemanager
	serverCommandParser
	serverInfo
	shortcutsConfig
	stringCommander
	system
	translatemanager
	ui
	uiadminmanager
	uiAffectShower
	uiAmuletSystem
	uiAttachMetin
	uibanpanel
	uibattlepass
	uibiologmanager
	uiboxloot
	uiCandidate
	uiCharacter
	uiChat
	uiCommon
	uicuberenewal
	uidiscarditemwindow
	uiDragonSoul
	uidungeoninfo
	uiDungeonTask
	uiEquipmentDialog
	uieventmanager
	uiExchange
	uifindletters
	uiGameButton
	uiGameOption
	uigayasystem
	uigmidleinterface
	uiGuild
	uiHandSwitcher
	uiHelp
	uiHunterMission
	uiInventory
	uiinventorymenu
	uiitemopener
	uiItemShopDialog
	uiitemsplitter
	uiLegendaryStones
	uilogschat
	uiluckybox
	uiMapNameShower
	uimarblemanager
	uiMessenger
	uiMiniMap
	uiMultipleAncientShopBuy
	uiMyShopDecoration
	uiofflineshop
	uiOption
	uioxdialog
	uiParty
	uiPhaseCurtain
	uiPickMoney
	uiPlayerGauge
	uiPointReset
	uiPopupSystem
	uipositionmanager
	uipreview
	uiPrivateShopBuilder
	uiQuest
	uirefactoredoptions
	uiRefine
	uirefineelement
	uiremovestone
	uiRestart
	uiSafebox
	uisashsystem
	uiScalingOption
	uiScriptLocale
	uiselectitem
	uiSelectMusic
	uiSelectSkill
	uiShamanSystem
	uishipdefenddungeon
	uiShop
	uiShopSearch
	uiswitchbot
	uiSystem
	uiSystemOption
	uiTarget
	uiTaskBar
	uitechnicalmaintenance
	uiteleportmanager
	uiTip
	uiTombola
	uiToolTip
	uitransmutation
	uiUploadMark
	uiWeb
	uiWhisper
	uizuopaneldialog
	ui_event
	util
	utility
	utils
	voicemanager
	zuopanelhelper
*/
void initrootlibManager();
#endif
